### ISSUE TITLE
Screenshots are dark with picom

### ISSUE THREAD

**Issue by kaihendry** [neXromancers/shotgun#19] opened 2020-05-31 06:47 UTC
https://s.natalian.org/2020-05-31/picom-killed.png - bright 

https://s.natalian.org/2020-05-31/with-picom.png - dark 

### Maintainer edit
In most cases this problem comes from picom's shadow effect. To fix it, you'll either want to disable shadows completely, or tell picom not to draw shadows on your selection tool.
For hacksaw, add this snippet to your configuration file:
```
shadow-exclude = [
  "name = 'hacksaw'"
]
```

**Comment by pickfire** [comment] 2020-05-31 07:50
I don't seemed to have any issues. @kaihendry Nice, you are here.

![1590911373](https://user-images.githubusercontent.com/4687791/83347250-71347680-a356-11ea-9dd2-e6853632fa68.png)

**Comment by 9ary** [comment] 2020-08-17 15:00
@kaihendry are you using hacksaw to select a screenshot region? Can you provide the info I asked for in https://github.com/neXromancers/hacksaw/issues/33#issuecomment-674932570?

**Comment by kaihendry** [comment] 2020-08-18 02:37
Sorry, I'm back to using https://github.com/lupoDharkael/flameshot

**Comment by 9ary** [comment] 2020-08-18 04:08
No problem, thanks anyway.

**Comment by chxp82q** [comment] 2020-09-01 22:04
@9ary the cause seems to be shadows with `picom`. Hacksaw does dim my screen and screenshots (with shotgun) do turn out dark.

[shadows disabled](https://imgur.com/YxtHwRz.png)
[shadows enabled](https://imgur.com/pzP5W4i.png)

[selection with shadows](https://imgur.com/t29fiFE.png)
[selection without shadows](https://imgur.com/dZI4wJy.png)

As you can see, the colors are much brighter without shadows.

Here's my shadow config for picom: 
```
# Shadow
shadow = true;
shadow-radius = 15;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.25;

#shadow-exclude = "(!name = 'rofi' && !class_g = 'Rofi' && !name = 'dunst' && !class_g = 'Dunst' && !class_g *?= 'Polybar')"

shadow-exclude = [
    "class_g *?= 'jgmenu'",
    "class_g *?= 'VirtualBox'",
    "class_g *?= 'Conky'",
    "class_g *?= 'Notify-osd'",
    "class_g *?= 'cairo-dock'",
    "class_g *?= 'trayer'",
    "class_g *?= 'navigator'",
    "class_g *?= 'Cairo-clock'",
    "class_g *?= 'Cairo-dock'",
    "class_g *?= 'Polybar'",
    "class_g *?= 'Docky'",
    "class_g = 'boox'",
    "class_g = 'hacksaw'",
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "window_type = 'dock'",
    "_GTK_FRAME_EXTENTS@:c"
];
```

**Comment by 9ary** [comment] 2020-09-01 22:07
Yes, that's what we worked out in the hacksaw thread. Note that hacksaw sets a window title, but not a class, so you might have better luck matching on that. I'll be closing this issue because it's not a shotgun problem.

**Closed as completed by 9ary** 2020-09-01 22:07 UTC
Labels: question, not our bug

**Comment by tkapias** [comment] 2022-03-14 13:29
All answers until the link to a commit (without comment in the issue thread) are false, so for people who will come here for a direct solution :

Add this to your picom config : 

```
shadow-exclude = [
  "name = 'hacksaw'"
]
```

**Comment by 9ary** [comment] 2022-03-14 13:35
Thanks for the tip! I'll add this information to the first post here and in the hacksaw issue.
