### ISSUE TITLE
Save to file and copy to clipboard?

### ISSUE THREAD

**Issue by DeeeeLAN** [neXromancers/shotgun#37] opened 2023-04-30 02:27 UTC
Hi, is it possible to save to a file and copy to the clipboard? If not, I guess I can figure out a way using the pipe output.

**Comment by 9ary** [comment] 2023-04-30 05:53
Absolutely! This isn't really specific to shotgun, but this is how you can modify the readme example to do this.

Your first option is to insert tee into the pipeline like so:
```sh
#!/bin/sh -e

selection=$(hacksaw -f "-i %i -g %g")
shotgun $selection - | tee file.png | xclip -t 'image/png' -selection clipboard
```
tee copies its standard input to its standard output and to all the file names you give it.

The other way to do this is to let shotgun write to a file first, then use xclip to copy to the clipboard afterwards:
```sh
#!/bin/sh -e

selection=$(hacksaw -f "-i %i -g %g")
shotgun $selection file.png
xclip -t 'image/png' -selection clipboard file.png
```

Unfortunately I'm unable to confirm whether these work because I've been using Wayland, and xclip doesn't seem to work there.

Closing because this is not a bug, feel free to ask more questions in this thread if something isn't clear.

**Closed as completed by 9ary** 2023-04-30 05:53 UTC
Labels: question
