### ISSUE TITLE
add lib target

### ISSUE THREAD

**Issue by DavidBJaffe** [neXromancers/shotgun#28] opened 2022-04-17 15:34 UTC
Could you please add a lib target so that people can access util and xwrap as crates?

**Comment by 9ary** [comment] 2022-04-17 15:41
This sounds like a partial duplicate of #6. I don't think it's a good idea to expose internal glue as public API. If you think this code would be useful for your project, I'd recommend copying and pasting it as necessary (just mind the license, which is MPL2).

**Comment by DavidBJaffe** [comment] 2022-04-17 15:54
Oops sorry for the duplicate.  I will copy the code.  Thank you for writing it!

**Comment by 9ary** [comment] 2022-04-17 15:55
You're welcome. :)

**Closed as completed by 9ary** 2022-04-17 15:55 UTC
Labels: enhancement, wontfix
