### ISSUE TITLE
Focused transparent windows

### ISSUE THREAD

**Issue by zephyrus92** [neXromancers/shotgun#23] opened 2021-01-14 07:36 UTC
Is there a way to capture the background along with the window when capturing the focused window? I use transparency with my terminal, and whenever I capture a focused terminal window, the background is completely black. The command I'm using is: `shotgun --id "$(xdotool getwindowfocus)"`. Same results if I use hacksaw to manually select a window with `shotgun --id "$(hacksaw -f %i)"`.

**Comment by 9ary** [comment] 2021-01-14 07:43
shotgun grabs the window's pixmap directly, including the alpha channel. You have a few options to capture the background:
- if your terminal supports fake transparency, you can try enabling it (not recommended)
- composite your wallpaper into the resulting image with imagemagick or similar
- capture the root window instead (using -g and omitting -i), note that the output will include any other window that may be in front of or behind your terminal

You can get the window geometry from xdotool with the following:
```shell
eval $(xdotool getwindowfocus getwindowgeometry --shell)
GEOMETRY="$WIDTHx$HEIGHT+$X+$Y"
```

**Comment by pickfire** [comment] 2021-01-14 15:55
I think there should be a FAQ for these kinds of things since this are edge cases but can be solved.

**Comment by 9ary** [comment] 2021-01-14 16:10
I was thinking of adding a contrib directory to the repo, so people could submit random scripts they make.

I think the question has been answered, and it's not a bug or feature request so I'm closing this.

**Closed as completed** 2021-01-14 16:11 UTC
Labels: question
